hoflaeden_suchen:
  fields:
    suchbegriff:
      example: "Käse"
      selector:
        text:
    angebot:
      example: "Kartoffeln"
      selector:
        text:
    zahlungsart:
      example: "TWINT"
      selector:
        text:
    nur_geoeffnet:
      example: true
      selector:
        boolean:
hoflaeden_in_naehe:
  fields:
    latitude:
      required: true
      example: 46.9480
      selector:
        number:
          min: -90
          max: 90
          step: "any"
          mode: box
    longitude:
      required: true
      example: 7.4474
      selector:
        number:
          min: -180
          max: 180
          step: "any"
          mode: box
    radius_meter:
      required: true
      example: 500
      selector:
        number:
          min: 0
          step: 1
          unit_of_measurement: m
          mode: box
    nur_geoeffnet:
      example: true
      selector:
        boolean:
    min_bewertung:
      example: 4
      selector:
        number:
          min: 0
          max: 5
          step: 1
          mode: box
